apiVersion: apps/v1
kind: Deployment
metadata:
  name: to_do_list-app
  labels:
    app: to_do_list-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to_do_list-app
  template:
    metadata:
      labels:
        app: to_do_list-app
    spec:
      containers:
      - name: To_do_list-app
        image: To_do_list_app:replaceImageTag
        ports:
        - containerPort: 8080
